version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: findmeadoc_db
    environment:
      POSTGRES_DB: findmeadoc
      POSTGRES_USER: findmeadoc_user
      POSTGRES_PASSWORD: iit@9009
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: