package com.example.find_me_a_doc_backend.domain;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.time.LocalTime;


@Entity
@Table(name = "appointments")
@Data
@NoArgsConstructor
public class Appointment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "doctor_id", nullable = false)
    private Doctor doctor;

    @ManyToOne
    @JoinColumn(name = "patient_id", nullable = false)
    private User patient;

    @Column(name = "appointment_date", nullable = false)
    private LocalDate appointmentDate;

    @Column(name = "start_time", nullable = false)
    private LocalTime appointmentTime;

    @Column(name = "status", nullable = false)
    private String status; // e.g., "Scheduled", "Completed", "Cancelled"

    @Column(name = "created_at", nullable = false)
    private LocalDate createdAt;

    @Column(name="payment_status", nullable = false)
    private String paymentStatus; // e.g., "Pending", "Paid", "Failed"

    @Column(name="ai_brief", length = 1000)
    private String aiBrief; // Brief summary generated by AI based on patient's symptoms and history
}
