package com.find_me_a_doc_backend.domain.models;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.time.LocalTime;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import com.fasterxml.jackson.databind.JsonNode;


@Entity
@Table(name = "appointments")
@Data
@NoArgsConstructor
public class Appointment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "doctor_id", nullable = false)
    private Doctor doctor;

    @ManyToOne
    @JoinColumn(name = "patient_id", nullable = false)
    private User patient;

    @Column(name = "appointment_date", nullable = false)
    private LocalDate appointmentDate;

    @Column(name = "start_time", nullable = false)
    private LocalTime appointmentTime;

    @Column(name = "status", nullable = false)
    private String status; // e.g., "Scheduled", "Completed", "Cancelled"

    @Column(name = "created_at", nullable = false)
    private LocalDate createdAt;

    @Column(name="payment_status", nullable = false)
    private String paymentStatus; // e.g., "Pending", "Paid", "Failed"

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "ai_brief", columnDefinition = "jsonb")
    private JsonNode aiBrief; // Brief summary generated by AI based on patient's symptoms and history
}
